version: '2.20.2'

services:
  spring-boot-app:
    image: openjdk:17-jdk-slim
    container_name: csw
    working_dir: /app
    volumes:
      - ./target/csw-0.0.1-SNAPSHOT.jar:/app/csw-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cosw
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    command: [ "java", "-jar", "csw-0.0.1-SNAPSHOT.jar" ]

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cosw

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
