version: '3.8'

services:
#  spring-boot-app:
#    image: ashtonchingovo/csw-springboot
#    container_name: csw-springboot
#    working_dir: /app
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cosw
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - db
#    restart: always

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cosw

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
